blogdemo/blog/home/models.py
 #

blogdemo/blog/home/__init__.py
#!flask/bin/python
#coding=utf-8
"""
define all the modules used in post, to make it easy to use the modules when
 register it.
"""

from flask import Blueprint

__all__ = ['views', 'models']

frontend = Blueprint('home_frontend', __name__, template_folder='templates')

blogdemo/blog/home/views.py
#!/flask/bin/python
#coding=utf-8

from datetime import datetime
import os
import json

from flask_wtf import Form
from wtforms import TextField, BooleanField, HiddenField, PasswordField, SubmitField, TextAreaField, validators
from wtforms.validators import required, EqualTo, email, ValidationError

from flask import Flask, Blueprint, redirect, Response, request, flash, g, \
    current_app, abort, url_for, session, render_template
from sqlalchemy import desc
# from flask.ext.principal import identity_changed, Identity, AnonymousIdentity

from blog.extensions import db, photos
from blog.permissions import auth, moderator, admin

from blog.account.models import User
from blog.post.models import Post
from blog.category.models import Category
from blog.tag.models import Tag
from blog.comment.models import Comment  # , comment_count

from blog.home import frontend


@frontend.route('/', methods=['GET', 'POST'])
@frontend.route('/index', methods=['GET', 'POST'])
def index():
    page = int(request.args.get('p', 1))
    post = Post.query.order_by(desc(Post.created_date)).paginate(page, per_page=5)
    # post = Post.query.order_by(desc(Post.created_date)).all()

    return render_template('home/index.html', page_obj=post)


@frontend.route('/post/<int:id>', methods=['GET', 'POST'])
def view(id):
    post = Post.query.get_or_404(id)
    comment = Comment.query.filter(Comment.post_id == post.id)
    return render_template('home/view.html', post=post, comment=comment)


@frontend.route('/error', methods=['GET', 'POST'])
def error():
    return render_template('home/error.html')

# @frontend.route('/post/<category>', methods=['GET', 'POST'])
# def list_by_cat(category):
#     post = Post.query.filter(Post.category_name == category).all()
#     return render_template('list_by_cat.html', post=post)

blogdemo/blog/home/templates/home/error.html
<!-- extend from base layout -->

{% extends "base.html" %}
{% from "_page.html" import message, paginate, status_label %}

{% block title %} Content {% endblock %}

{% block body %}
    <h1>NOT SET UP YET</h1>
{% endblock %}

blogdemo/blog/home/templates/home/index.html
<!-- extend from base layout -->

{% extends "base.html" %}
{% from "_page.html" import message, paginate, status_label %}

{% block title %} BlogList {% endblock %}

{% block body %}

<div id="body">
    <div id="post" class="post">
        <h1>Welcome to the preposterous blog, {{ g.user.nickname }}<h1>
        <hr/>
        {% for post in page_obj.items %}
        <h2 class="post-title"><a href="{{ url_for('home_frontend.view', id=post.id) }}">{{ post.title }}</a></h2>
        <div class="post-info">
            <!--here show the post under names, catagories-->
            <abbr title="{{ post.created_date }}" class="time">{{ post.created_date }}</abbr> | By <a href="{{ url_for('home_frontend.error') }}">{{ post.author }}</a>, Category: 
            <a href="{{ url_for('home_frontend.error') }}">{{ post.category_name }}</a>
        </div>
        <div class="post-body">
            <p>{{ post.content | safe}}</p>
            <a href="{{ url_for('home_frontend.view', id=post.id) }}">read more ...</a>
            | {{ post.comment | length }} comments
        </div>
        <span class="tag-links">
            <span class="tagsearch">Tags : </span> 
            {% for tag in post.tag %}
                <a href="{{ url_for('home_frontend.error') }}" title="post in tag" rel="tag">{{ tag.name }}</a>, 
            {% endfor %}
        </span>
        {% endfor %}
    </div>
</div>

{{paginate(page_obj)}}
{% endblock %}

blogdemo/blog/home/templates/home/view.html
<!-- extend from base layout -->

{% extends "base.html" %}
{% from "_page.html" import message, paginate, status_label %}

{% block title %} Content {% endblock %}

{% block body %}

<div id="body">
    <div id="body_top-{{ post.id }}">
        <h2>CONTENT VIEWS</h2>
    </div>

    <div id="body_middle">
        <h2 class="post-title">{{ post.title }}</h2>
        <div class="post-info">
            <!--here show the post under names, catagories-->
            <p>Post by {{ post.author }}
            <abbr title="{{ post.created_date }}" class="time"> at {{ post.created_date }}</abbr>. 
            Category : {{ post.category_name }}</p>
        </div>
        <div class="post-body">
            <p>{{ post.content | safe}}</p>
        </div>
        <span class="tag-links">
            <span class="tagsearch">Tags : </span> 
            {% for tag in post.tag %}
                {{ tag.name }}, 
            {% endfor %}
        </span>
    </div>
    <div id="body_extend">
        {% if g.user.id == post.user_id %}
            <a href="{{ url_for('post_backend.edit', id=post.id) }}">edit</a>
            <a href="{{ url_for('post_backend.delete', id=post.id) }}">delete</a>
        {% endif %}
        <hr />
    </div>
    <div id="comment">
        <h3>COMMENTS</h3>
        {% for comment in comment %}
            
            <abbr title="{{ post.created_date }}" class="time">{{ comment.created_date }}</abbr> | By <a href="{{ url_for('home_frontend.error') }}">{{ comment.author }}</a> | 
            {% if comment.author == g.user %}
                <a href="{{ url_for('comment_frontend.edit', id=comment.id) }}">edit</a>
                <a href="{{ url_for('comment_frontend.delete', id=comment.id) }}">delete</a>
            {% endif %}
            <p>{{ comment.content | safe}}</p>

        {% endfor %}
        <hr />
    </div>
    <div id="newcomment">
        <a href="{{ url_for('comment_frontend.new', post_id=post.id) }}">Add Comment</a>
    </div>
</div>

{#{paginate(page_obj)}#}
{% endblock %}