blogdemo/blog/category/models.py
#!/flask/bin/python
#coding=utf-8

from datetime import datetime
import os
import hashlib
import json

from werkzeug import cached_property

from flask import abort, current_app, g, url_for
from flask.ext.sqlalchemy import SQLAlchemy, BaseQuery
from flask.ext.principal import RoleNeed, UserNeed, Permission

from blog.extensions import db
from blog.permissions import moderator, admin


class CatQuery(BaseQuery):
    def jsonify(self):
        for category in self.all():
            yield category.json

    def get_or_404(self, *args, **kwargs):
        try:
            return self.get(*args, **kwargs)
        except:
            abort(404)


class Category(db.Model):
    query_class = CatQuery

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.Text)

    def __unicode__(self):
        return self.name

blogdemo/blog/category/forms.py
#!/flask/bin/python
#coding=utf-8

from flask_wtf import Form
from wtforms import TextField, BooleanField, HiddenField, PasswordField, \
    SubmitField, TextAreaField, SelectField, validators
from wtforms.validators import Required, EqualTo, email, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from blog.extensions import db

from blog.account.models import User
from blog.post.models import Post
from blog.category.models import Category


class CategoryForm(Form):
    name = TextField('Name', [validators.required(), validators.length(min=1, max=240)])
    description = TextAreaField('Description', [validators.required()])
    next = HiddenField()

blogdemo/blog/category/__init__.py
#!flask/bin/python
#coding=utf-8
"""
define all the modules used in post, to make it easy to use the modules when
 register it.
"""

from flask import Blueprint

__all__ = ['views', 'models']

frontend = Blueprint('category_frontend', __name__, template_folder='templates')
backend = Blueprint('category_backend', __name__, url_prefix='/admin', template_folder='templates')

blogdemo/blog/category/views.py
#!/flask/bin/python
#coding=utf-8

from datetime import datetime
import os
import json

from flask_wtf import Form
from wtforms import TextField, BooleanField, HiddenField, PasswordField, SubmitField, TextAreaField, validators
from wtforms.validators import required, EqualTo, email, ValidationError

from flask import Flask, Blueprint, redirect, Response, request, flash, g, current_app, abort, url_for, session, render_template
# from flask.ext.principal import identity_changed, Identity, AnonymousIdentity

from blog.extensions import db, photos
from blog.permissions import auth, moderator, admin

from blog.account.models import User
from blog.post.models import Post

from blog.category import backend, frontend
from blog.category.models import Category
from blog.category.forms import CategoryForm


@backend.route('/category', methods=['GET', 'POST'])
@auth.require(401)
def index():
    category = Category.query.all()
    return render_template('category/index.html', category=category)


@backend.route('/category/new', methods=['GET', 'POST'])
@auth.require(401)
def new():
    catlist = Category.query.all()
    form = CategoryForm()
    category = Category()
    if form.validate_on_submit():
        form.populate_obj(category)
        db.session.add(category)
        db.session.commit()
        return redirect(url_for('category_backend.index'))
    return render_template('category/new.html', form=form, catlist=catlist)


@backend.route('/category/<int:id>/edit', methods=['GET', 'POST'])
@auth.require(401)
def edit(id):
    category = Category.query.get_or_404(id)
    if not category:
        return 404
    form = CategoryForm(request.form, category)

    if form.validate_on_submit():
        form.populate_obj(category)
        db.session.add(category)
        db.session.commit()
        return redirect(url_for('category_backend.index'))
    return render_template('category/edit.html', form=form)


@backend.route('category/<int:id>/delete', methods=['GET', 'POST'])
@auth.require(401)
def delete(id):
    category = Category.query.get_or_404(id)
    db.session.delete(category)
    db.session.commit()
    return redirect(url_for('category_backend.index'))


@backend.route('/category/<name>', methods=['GET', 'POST'])
def view(name):
    post = Post.query.filter(Post.category_name == name).filter(Post.user_id == g.user.id).all()
    return render_template('category/view.html', post=post)

blogdemo/blog/category/templates/category/edit.html
<!-- extend from layout -->
{% extends "layout.html" %}
{% block title %}editpost{% endblock %}

{% block content %}
<div id="body">
    <div id="body_top">
        <ul id="breadcrumb" class="breadcrumb">
            <li><a href="{{ url_for('account_backend.manage', id=g.user.id) }}">{{ g.user.nickname }}</a></li>
            <li><a href="{{ url_for('admin_backend.index') }}">Admin</a></li>
            <li><a href="{{ url_for('category_backend.index') }}">Category</a> &nbsp;&gt;</li>
            <li>Edit</li>
        </ul>
        <hr/>
    </div>
    <div id="body_middle">
        <form method="POST" action="">
            {{ form.hidden_tag() }}

            {{ form.name.label }}
            {{ form.name }}

            {{ form.description.label }}
            {{ form.description }}<br/>

            <input id="submit", name="submit", class="btn btn-inverse", type="submit", value="Save changes">
        </form>
    </div>

</div>
{% endblock %}

blogdemo/blog/category/templates/category/index.html
<!-- extend from layout -->

{% set location = 'category' %}
{% extends 'layout.html' %}
{% from '_page.html' import message, paginate, status_label %}
{% block title %}mycategory{% endblock %}
{% block content %}
<div class="content">
    <div id="body_top" class="Category">
        <ul id="breadcrumb" class="breadcrumb">
            <li><a href="{{ url_for('account_backend.manage', id=g.user.id) }}">{{ g.user.nickname }}</a></li>
            <li><a href="{{ url_for('admin_backend.index') }}">Admin</a></li>
            <li>Category</li>
        </ul>
        <hr/>
    </div>
    <div id="body_middle">

        <div class="category-list">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>NAME</th>
                    <th>DESCRIPTION</th>
                    <th>ACTIVE</th>
                </tr>
            </thead>
            <tbody>
                {% for category in category %}
                    <tr>
                        <td><a href="{{ url_for('category_backend.view', name=category.name)}}">{{ category.name }}</td>
                        <td>{{ category.description }}</td>
                        <td>
                            {% if g.user.id %}
                                <a href="{{ url_for('category_backend.edit', id=category.id) }}">edit</a>
                                <a href="{{ url_for('category_backend.delete', id=category.id) }}">delete</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
        <div class="new category">
            <a href="{{ url_for('category_backend.new') }}" class="btn btn-inverse">Create New Category</a>
        </div>
    </div>
</div>
{% endblock %}

blogdemo/blog/category/templates/category/new.html
<!-- extend from layout -->
{% extends "layout.html" %}
{% block title %}newcategory{% endblock %}

{% block content %}
<div class="content">
    <div id="body_top" class="Category">
        <ul id="breadcrumb" class="breadcrumb">
            <li><a href="{{ url_for('account_backend.manage', id=g.user.id) }}">{{ g.user.nickname }}</a></li>
            <li><a href="{{ url_for('admin_backend.index') }}">Admin</a></li>
            <li><a href="{{ url_for('category_backend.index') }}">Category</a></li>
            <li>Create New Category</li>
        </ul>
        <hr/>
    </div>
    <div id="body_middle">
        <form action="", method="POST">
            {{ form.hidden_tag() }}

            {{ form.name.label }}
            {{ form.name }}

            {{ form.description.label }}
            {{ form.description }}<br/>

            <input id="submit", name="submit", class="btn btn-inverse", type="submit", value="Create Category">
        </form>
    </div>
    <div id="showcategory">
        {% for category in catlist %}
        <table>
            <tr>    
                <th>{{ category.name }}</th><td>{{ category.description }}</td>
            </tr>
        </table>
        {% endfor %}
    </div>
</div>
{% endblock %}

blogdemo/blog/category/templates/category/view.html
<!-- extend from layout -->

{% extends 'layout.html' %}
{% from '_page.html' import message, paginate, status_label %}
{% block title %}postbycat{% endblock %}

{% block content %}
<div class="content">
    <div id="body_top">
        <ul id="breadcrumb" class="breadcrumb">
            <li><a href="{{ url_for('account_backend.manage', id=g.user.id) }}">{{ g.user.nickname }}</a></li>
            <li><a href="{{ url_for('admin_backend.index') }}">Admin</a></li>
            <li><a href="{{ url_for('category_backend.index') }}">Category</a></li>
            <li>Post by Category</li>
        </ul>
        <hr/>
    </div>
    <div id="body_middle">

        <div class="post-list">
        <table style="width:1000px">
            <thead>
                <tr>
                    <th>TITLE</th>
                    <th>AUTHOR</th>
                    <th>CREATED TIME</th>
                    <th>CATEGORY</th>
                    <th>TAG</th>
                    <th>ACTIVE</th>
                </tr>
            </thead>
            <tbody>
                {% if name == name %}
                {% for post in post %}
                    {% if g.user.id == post.user_id %}
                    <tr>
                        <td><a href="{{ url_for('post_backend.view', id=post.id) }}">{{ post.title }}</a></td>
                        <td>{{ post.author.nickname }}</td>
                        <td>{{ post.created_date }}</td>
                        <td>{{ post.category_name }}</td>
                        <td><span class="tag-links">Tags : 
                            {% for tag in post.tag %}
                                <a href="" title="post in tag" rel="tag">{{ tag.name }}</a>, 
                            {% endfor %}
                            </span>
                        </td>
                        <td>

                                <a href="{{ url_for('post_backend.edit', id=post.id) }}">edit</a>
                                <a href="{{ url_for('post_backend.delete', id=post.id) }}">delete</a>                            
                        </td>
                    </tr>
                    {% endif %}
                {% endfor %}
                {% endif %}
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock %}