blogdemo/blog/admin/models.py
#

blogdemo/blog/home/models.py
 #

blogdemo/blog/account/forms.py
#!/flask/bin/python
#coding=utf-8

from flask_wtf import Form
from wtforms import TextField, BooleanField, HiddenField, PasswordField, SubmitField, TextAreaField, validators
from wtforms.validators import required, EqualTo, email, ValidationError
from flask import Flask
from flask.ext.babel import gettext

from blog.account.models import User
from blog.extensions import db


class LoginForm(Form):
    account = TextField(u'Username', [validators.required()])
    password = PasswordField(u'Password')
    remember = BooleanField(u'remember_me', default=False)
    next = HiddenField()
    submit = SubmitField('Login')


class RegisterForm(Form):
    account = TextField(u'Username', [validators.required(),
                                      validators.length(min=4, max=25)])
    nickname = TextField(u'Nickname', [validators.required()])
    email = TextField(u'Email Address', [validators.required(),
                                         validators.length(min=6, max=35)])
    password = PasswordField(u'Password', [
        validators.required(),
        validators.EqualTo(u'confirm', message='Passwords must match')
    ])
    confirm = PasswordField(u'Repeat Password')
    accept_tos = BooleanField(u'I accept the TOS', [validators.required()])
    next = HiddenField()
    submit = SubmitField('Create account')

    def validate_username(self, field):
        user = User.query.filter(User.account.like(field.data)).first()
        if user:
            raise ValidationError("The username is existing")

    def validate_email(self, field):
        user = User.query.filter(User.email.like(field.data)).first()
        if user:
            raise ValidationError("The email is existing")


class AccountForm(Form):
    account = TextField(u'Username', [validators.required()])
    email = TextField(u'Email Address', [validators.required()])
    submit = SubmitField('Save')


class ProfileForm(Form):
    first_name = TextField(u'First Name', [validators.required()])
    last_name = TextField(u'Last Name', [validators.required()])
    address = TextField(u'Address', [validators.required()])
    city = TextField(u'city', [validators.required()])
    phone = TextField(u'Phone', [validators.required()])
    submit = SubmitField('Save')


class ResetPwForm(Form):
    password = PasswordField(u'Old Password', [validators.required()])
    newpassword = PasswordField(u'New Password', [validators.required()])
    confirm = PasswordField(u'Repeat New Password', [
        validators.required(),
        validators.EqualTo('newpassword', message='Passwords must match')])
    submit = SubmitField('Submit')

blogdemo/blog/category/forms.py
#!/flask/bin/python
#coding=utf-8

from flask_wtf import Form
from wtforms import TextField, BooleanField, HiddenField, PasswordField, \
    SubmitField, TextAreaField, SelectField, validators
from wtforms.validators import Required, EqualTo, email, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from blog.extensions import db

from blog.account.models import User
from blog.post.models import Post
from blog.category.models import Category


class CategoryForm(Form):
    name = TextField('Name', [validators.required(), validators.length(min=1, max=240)])
    description = TextAreaField('Description', [validators.required()])
    next = HiddenField()

blogdemo/blog/comment/forms.py
#!/flask/bin/python
#coding=utf-8

from flask_wtf import Form
from wtforms import TextField, BooleanField, HiddenField, PasswordField, \
    SubmitField, TextAreaField, SelectField, validators
from wtforms.validators import Required, EqualTo, email, ValidationError

from blog.extensions import db

from blog.account.models import User
from blog.post.models import Post
from blog.comment.models import Comment


class CommentForm(Form):
    nickname = TextField(u'Nickname')
    email = TextField(u'Email')
    content = TextAreaField(u'Content', [validators.required()])
    submit = SubmitField(u'Add comment')
    cancel = SubmitField(u'Cancel')
    next = HiddenField()

blogdemo/blog/tag/forms.py
#!/flask/bin/python
#coding=utf-8

from flask_wtf import Form
from wtforms import TextField, BooleanField, HiddenField, PasswordField, \
    SubmitField, TextAreaField, SelectField, validators
from wtforms.validators import Required, EqualTo, email, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from blog.extensions import db

from blog.account.models import User
from blog.post.models import Post
from blog.tag.models import Tag


class TagForm(Form):
    name = TextField('TagName', [validators.required(), validators.length(min=1, max=60)])
    next = HiddenField()
    

blogdemo/blog/__init__.py
#!flask/bin/python
#coding:utf-8

import os
import json
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
import datetime

from werkzeug import import_string
from flask import Flask, g, session, request, flash, redirect, jsonify, url_for, render_template
from flask.ext.principal import Principal, RoleNeed, UserNeed, identity_loaded
from flaskext.uploads import configure_uploads

from blog.extensions import db, mail, photos
from blog.account.models import User
#from blog.post.models import Post

DEFAULT_APP_NAME = 'blog'

### register the imported modules here, using strings, the modules import are shown later
DEFAULT_BLUEPRINTS = ['blog.account:frontend',
                      'blog.account:backend',
                      'blog.post:frontend',
                      'blog.post:backend',
                      'blog.category:frontend',
                      'blog.category:backend',
                      'blog.tag:frontend',
                      'blog.tag:backend',
                      'blog.comment:frontend',
                      'blog.comment:backend',
                      'blog.home:frontend',
                      'blog.admin:backend'
                      ]


def create_app(config=None, blueprints=None):

    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS
    app = Flask(DEFAULT_APP_NAME)
    app.config.from_pyfile(config)

    # extension for db creation
    configure_extensions(app)
    configure_identity(app)
    # configure_logging(app)
    configure_before_handlers(app)

    # upload & set the max size
    configure_uploads(app, (photos,))
    # patch_request_class(app, size=16777216)

    # register the module to app, the last one of all the configure
    configure_blueprints(app, blueprints)

    return app


### register modules with app, without url_prefix for now; and import modules into the package string

def configure_blueprints(app, blueprints):
    blueprints_list = []
    packages_list = []

    for name in blueprints:
        # put module into blueprint
        blueprint = import_string(name)
        blueprints_list.append(blueprint)
        # print blueprint.import_name
        package = import_string(blueprint.import_name)
        packages_list.append(package)

#   if isinstance(packages_list,(str,list)):
#       return packages_list
#   else: packages_list=packages_list.split()

    for package in list(set(packages_list)):
        for member_name in getattr(package, '__all__', []):  # get obj.name from __all__ py files
            __import__('%s.%s' % (package.__name__, member_name))

    for blueprint in list(set(blueprints_list)):
        app.register_blueprint(blueprint)


def configure_extensions(app):
    db.init_app(app)
    mail.init_app(app)


### define g.user

def configure_identity(app):

    principal = Principal(app)

    @identity_loaded.connect_via(app)
    def on_identity_loaded(sender, identity):
        g.user = User.query.from_identity(identity)


### call g thread local from authenticated user

def configure_before_handlers(app):
    @app.before_request
    def authenticate():
        g.user = getattr(g.identity, 'user', None)

blogdemo/blog/account/__init__.py
#!flask/bin/python
#coding=utf-8
'''
define all the modules used in post, to make it easy to use the modules when
 register it.
'''

from flask import Blueprint

__all__ = ['views', 'models']

frontend = Blueprint('account_frontend', __name__, template_folder='templates')
backend = Blueprint('account_backend', __name__, url_prefix='/account', template_folder='templates')

blogdemo/blog/account/views.py
from datetime import datetime
import os

from flask import Blueprint, redirect, Response, request, flash, g, current_app, abort, url_for, session, render_template
from flask.ext.principal import identity_changed, Identity, AnonymousIdentity
from sqlalchemy.ext.hybrid import hybrid_property

from blog.account import frontend, backend
from blog.account.forms import LoginForm, RegisterForm, AccountForm, ProfileForm, ResetPwForm
from blog.account.models import User, Profile
from blog.extensions import db
from blog.permissions import auth, moderator, admin


### When guest comes to the blog, inquire for login or register

@frontend.route('/login', methods=['GET', 'POST'])  # request $args$ value if data is submitted as GET
def login():
    form = LoginForm(account=request.args.get('account', None),
                     next=request.args.get('next', None))  # better explicit than implicit

    if form.validate_on_submit():
        user, authenticated = User.query.authenticate(form.account.data, form.password.data)
        if user and authenticated:
            session.permanent = form.remember.data
            # represent if the user is stored/loaded from session
            identity_changed.send(current_app._get_current_object(),
                                  identity=Identity(user.id))
            flash('Welcome back, %s' % user.account, 'success')

            next_url = form.next.data

            if not next_url or next_url == request.path:
                next_url = url_for('admin_backend.index')
            return redirect(next_url)
        else:
            flash('Sorry, invalid login', 'error')
    return render_template('account/login.html', title='Sign In', form=form)


@frontend.route('/logout')
def logout():
    flash(u'You have logout', 'success')
    identity_changed.send(current_app._get_current_object(),
                          identity=AnonymousIdentity())
    next_url = request.args.get('next', '')

    if not next_url or next_url == request.path:
        next_url = url_for('account_frontend.login')
    return redirect(next_url)


@frontend.route('/register', methods=['GET', 'POST'])  # request $form$ value if data is submitted as POST
def register():
    form = RegisterForm(next=request.args.get('next', None))
    if form.validate_on_submit():  # here delete the condition request.method=='POST'
        user = User()  # form.account.data, form.email.data, form.password.data)
        form.populate_obj(user)  # populates the attributes of the passed obj with data from the form fields
        db.session.add(user)
        db.session.commit()
        flash('Thank you for registering')
        return redirect(url_for('admin_backend.index'))
    return render_template('account/register.html', form=form)


@backend.route('/<int:id>/manage', methods=['GET', 'POST'])
@auth.require(401)
def manage(id):
    user = User.query.get_or_404(id)
    profile = Profile.query.get(user.id)
#page = int(request.args.get('p',1))
#page_obj = User.query.order_by('-id').paginage(page, per_page=10)
    return render_template('account/manage.html', user=user, profile=profile)  # , page_obj=page_obj)


@backend.route('/<int:id>/manage/profile', methods=['GET', 'POST'])
@auth.require(401)
def profile(id):
    user = User.query.get_or_404(id)
    if user:
        profile = Profile(user_id=user.id)
        form = ProfileForm(first_name=profile.first_name,
                           last_name=profile.last_name,
                           addresss=profile.address,
                           city=profile.city,
                           phone=profile.phone)
    if form.validate_on_submit():
        form.populate_obj(profile)
        db.session.add(profile)
        db.session.commit()
        flash('Informations have been updated')
        return redirect(url_for('account_backend.manage', id=user.id))

    return render_template('account/profile.html', form=form)


@backend.route('/<int:id>/manage/edit', methods=['GET', 'POST'])
@auth.require(401)
def edit(id):
    user = User.query.get_or_404(id)
    form = ResetPwForm(password=request.args.get('password', None))
    if form.validate_on_submit():
        authenticated = user.check_password(form.password.data)

        if authenticated:
            user.password = form.newpassword.data
            db.session.commit()
            flash("Password is changed successfully", "success")
            next_url = url_for('account_backend.manage', id=user.id)
            return redirect(next_url)
        else:
            flash('Incorrect old password')
    return render_template('account/edit.html', form=form, user=user)

blogdemo/blog/admin/__init__.py
#!flask/bin/python
#coding=utf-8
"""
define all the modules used in post, to make it easy to use the modules when
 register it.
"""

from flask import Blueprint

__all__ = ['views', 'models']

backend = Blueprint('admin_backend', __name__, url_prefix='/admin', template_folder='templates')

blogdemo/blog/admin/views.py
#!/flask/bin/python
#coding=utf-8

from flask_wtf import Form
from wtforms import TextField, BooleanField, HiddenField, PasswordField, SubmitField, TextAreaField, validators
from wtforms.validators import required, EqualTo, email, ValidationError

from flask import Flask, Blueprint, redirect, Response, request, flash, g, current_app, abort, url_for, session, render_template

from blog.extensions import db, photos
from blog.permissions import auth, moderator, admin

from blog.admin import backend

from blog.account.models import User
from blog.post.models import Post


@backend.route('/', methods=['GET', 'POST'])
# @auth.required(401)
def index():
    return render_template('admin/index.html')

blogdemo/blog/category/__init__.py
#!flask/bin/python
#coding=utf-8
"""
define all the modules used in post, to make it easy to use the modules when
 register it.
"""

from flask import Blueprint

__all__ = ['views', 'models']

frontend = Blueprint('category_frontend', __name__, template_folder='templates')
backend = Blueprint('category_backend', __name__, url_prefix='/admin', template_folder='templates')

blogdemo/blog/category/views.py
#!/flask/bin/python
#coding=utf-8

from datetime import datetime
import os
import json

from flask_wtf import Form
from wtforms import TextField, BooleanField, HiddenField, PasswordField, SubmitField, TextAreaField, validators
from wtforms.validators import required, EqualTo, email, ValidationError

from flask import Flask, Blueprint, redirect, Response, request, flash, g, current_app, abort, url_for, session, render_template
# from flask.ext.principal import identity_changed, Identity, AnonymousIdentity

from blog.extensions import db, photos
from blog.permissions import auth, moderator, admin

from blog.account.models import User
from blog.post.models import Post

from blog.category import backend, frontend
from blog.category.models import Category
from blog.category.forms import CategoryForm


@backend.route('/category', methods=['GET', 'POST'])
@auth.require(401)
def index():
    category = Category.query.all()
    return render_template('category/index.html', category=category)


@backend.route('/category/new', methods=['GET', 'POST'])
@auth.require(401)
def new():
    catlist = Category.query.all()
    form = CategoryForm()
    category = Category()
    if form.validate_on_submit():
        form.populate_obj(category)
        db.session.add(category)
        db.session.commit()
        return redirect(url_for('category_backend.index'))
    return render_template('category/new.html', form=form, catlist=catlist)


@backend.route('/category/<int:id>/edit', methods=['GET', 'POST'])
@auth.require(401)
def edit(id):
    category = Category.query.get_or_404(id)
    if not category:
        return 404
    form = CategoryForm(request.form, category)

    if form.validate_on_submit():
        form.populate_obj(category)
        db.session.add(category)
        db.session.commit()
        return redirect(url_for('category_backend.index'))
    return render_template('category/edit.html', form=form)


@backend.route('category/<int:id>/delete', methods=['GET', 'POST'])
@auth.require(401)
def delete(id):
    category = Category.query.get_or_404(id)
    db.session.delete(category)
    db.session.commit()
    return redirect(url_for('category_backend.index'))


@backend.route('/category/<name>', methods=['GET', 'POST'])
def view(name):
    post = Post.query.filter(Post.category_name == name).filter(Post.user_id == g.user.id).all()
    return render_template('category/view.html', post=post)

blogdemo/blog/comment/__init__.py
#!flask/bin/python
#coding=utf-8
"""
define all the modules used in post, to make it easy to use the modules when
 register it.
"""

from flask import Blueprint

__all__ = ['views', 'models']

frontend = Blueprint('comment_frontend', __name__, template_folder='templates')
backend = Blueprint('comment_backend', __name__, url_prefix='/admin', template_folder='templates')

blogdemo/blog/templates/_page.html
{% macro paginate(page_obj) %}
{% if page_obj.pages > 1 %}
<div class="pagination .pagination-mini">
<ul class="pager">
	<li {% if not page_obj.has_prev %} class="disabled" {% endif %}>
		<a href="?p={{page_obj.page-1}}">Prev</a>
	</li>
	{% for i in range(1, page_obj.pages+1) %}
	<li {% if i == page_obj.page %} class="active" {% endif %}>
		<a href="?p={{i}}">{{i}}</a>
	</li>
	{% endfor %}
	<li {% if not page_obj.has_next %}class="disabled"{% endif %}>
		<a href="?p={{page_obj.page+1}}">Next</a></li>
</ul>
</div>
{% endif %}
{% endmacro %}

{% macro status_label(status, status_message) %}
{% if status == 1 %}
<span class="label label-success">{{status_message}}</span>
{% elif status == 0 %}
<span class="label">{{status_message}}</span>
{% elif status == 2 %}
<span class="label label-warning">{{status_message}}</span>
{% elif status == 3 %}
<span class="label label-important">{{status_message}}</span>
{% endif %}
{% endmacro %}

{% macro message() %}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class = "msg">
	{% for category,message in messages %}
	<div class="alert alert-{{category}}">
		<button class="close" data-dismiss="alert" type="button">x</button>
		{{ message }}
	</div>
	{% endfor %}
</div>
{% endif %}
{% endwith %}
{% endmacro %}

{% macro render_errors(field) %}
{% if field.errors %}
	<ul class=errors>
	{% for error in field.errors %}
		<li><span style="color:red;">[{{ error }}]</span></li>
	{% endfor %}
	</ul>
{% endif %}
</dd>
{% endmacro %}

blogdemo/blog/templates/base.html
{% from "_page.html" import message %}
<!doctype html>
<html lang="zh-cn">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	{% if title %}
	<title>MyBlog-{% block title %}{% endblock %}</title>	
	{% else %}
	<title>Wel to my universe</title>
	{% endif %}

	<!-- Bootstrap -->
	<link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
	{% block css %}
	<link href="/static/kindeditor/themes/default/default.css" rel="stylesheet" />
	{% endblock %}

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://cdn.bootcss.com/jquery/1.10.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/js/bootstrap.min.js"></script>
	{% block js %}
	{% endblock %}
	
</head>

<body>
<div id="header" class="container">
	<div id="top">
		<div class="headline">
			<a href="/"><h1>{{ config['BLOG_NAME'] }}</h1></a>
			<p><span class="nav pull-right">
				{% if g.user %}
					<a href="{{ url_for('account_frontend.logout') }}">Logout</a>
					<a href="{{ url_for('admin_backend.index') }}">My Blog</a>
				{% else %}
					<a href="{{ url_for('account_frontend.login') }}">Login</a>
					<a href="{{ url_for('account_frontend.register') }}">Sign Up</a>
				{% endif %}
			</span></p>
		</div>
	</div>
</div>

<div id="main" class="container">
	<div class="wrapper">
		{{message()}}
		{% block body %}
		{% endblock %}
	</div>

	<div id="sidebar" class="wrapper">
		{% block sidebar %}
		{% endblock %}
	</div>

	<div id="footer">
		{% block footer %}
		{% endblock %}
	</div>
</div>

</body>

</html>

blogdemo/blog/templates/layout.html
{% extends 'base.html' %}

{% block sidebar %}
<div class="row">
	<div class="col-md-2">
		<a class="btn btn-primary" {% if location == 'submit' %}{% endif %} href="{{ url_for('post_backend.new') }}">New Post</a>

		<ul class="nav nav-tabs nav-stacked">
			<li{% if location == 'overview' %} class=="active" {% endif %}>
				<a href="{{ url_for('admin_backend.index') }}">Overview</a>
			</li>
			<li{% if location == 'post' %} class=="active" {% endif %}>
				<a href="{{ url_for('post_backend.index') }}">Post</a>
			</li>
			<li{% if location == 'category' %} class=="active" {% endif %}>
				<a href="{{ url_for('category_backend.index') }}">Category</a>
			</li>
			<li{% if location == 'tag' %} class=="active" {% endif %}>
				<a href="{{ url_for('tag_backend.index') }}">Tag</a>
			</li>
			<li{% if location == 'user' %} class=="active" {% endif %}>
				<a href="{{ url_for('account_backend.manage', id=g.user.id) }}">Profiles</a>
			</li>
		</ul>
	</div>
	<div class="col-md-10">
		{% block content %}
		{% endblock %}
	</div>
</div>
{% endblock %}