blogdemo/blog/tag/models.py
#!/flask/bin/python
#coding=utf-8

from datetime import datetime
import os
import hashlib
import json

from werkzeug import cached_property

from flask import abort, current_app, g, url_for
from flask.ext.sqlalchemy import SQLAlchemy, BaseQuery
from flask.ext.principal import RoleNeed, UserNeed, Permission

from blog.extensions import db
from blog.permissions import moderator, admin


class TagQuery(BaseQuery):
    def jsonify(self):
        for tag in self.all():
            yield tag.json

    def get_or_404(self, *args, **kwargs):
        try:
            return self.get(*args, **kwargs)
        except:
            abort(404)


class Tag(db.Model):
    query_class = TagQuery

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True, nullable=False)

    def __unicode__(self):
        return self.name


# class TagPost(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     postid = db.Column(db.Integer, db.ForeignKey('post.id', ondelete='CASCADE'), nullable=False)
#     tagid = db.Column(db.Integer, db.ForeignKey('tag.id'), nullable=False)

#     post = db.relationship('Post', backref='TagQuery', lazy='joined')
#     tag = db.relationship('Tag', backref='TagQuery', lazy='joined')

blogdemo/blog/tag/forms.py
#!/flask/bin/python
#coding=utf-8

from flask_wtf import Form
from wtforms import TextField, BooleanField, HiddenField, PasswordField, \
    SubmitField, TextAreaField, SelectField, validators
from wtforms.validators import Required, EqualTo, email, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from blog.extensions import db

from blog.account.models import User
from blog.post.models import Post
from blog.tag.models import Tag


class TagForm(Form):
    name = TextField('TagName', [validators.required(), validators.length(min=1, max=60)])
    next = HiddenField()
    

blogdemo/blog/tag/__init__.py
#!flask/bin/python
#coding=utf-8
"""
define all the modules used in post, to make it easy to use the modules when
 register it.
"""

from flask import Blueprint

__all__ = ['views', 'models']

frontend = Blueprint('tag_frontend', __name__, template_folder='templates')
backend = Blueprint('tag_backend', __name__, url_prefix='/admin', template_folder='templates')

blogdemo/blog/tag/views.py
#!/flask/bin/python
#coding=utf-8

from datetime import datetime
import os
import json

from flask_wtf import Form
from wtforms import TextField, BooleanField, HiddenField, PasswordField, SubmitField, TextAreaField, validators
from wtforms.validators import required, EqualTo, email, ValidationError

from flask import Flask, Blueprint, redirect, Response, request, flash, g, current_app, abort, url_for, session, render_template
# from flask.ext.principal import identity_changed, Identity, AnonymousIdentity

from blog.extensions import db, photos
from blog.permissions import auth, moderator, admin

from blog.account.models import User
from blog.post.models import Post

from blog.tag import backend, frontend
from blog.tag.models import Tag
from blog.tag.forms import TagForm


@backend.route('/tag', methods=['GET', 'POST'])
@auth.require(401)
def index():
    # post = Post.query.filter(Post.user_id == g.user.id).all()

    tag = Tag.query.all()
    return render_template('tag/index.html', tag=tag)


@backend.route('/tag/new', methods=['GET', 'POST'])
@auth.require(401)
def new():
    taglist = Tag.query.all()
    form = TagForm()
    tag = Tag()
    if form.validate_on_submit():
        form.populate_obj(tag)
        db.session.add(tag)
        db.session.commit()
        return redirect(url_for('tag_backend.index'))
    return render_template('tag/new.html', form=form, taglist=taglist)


@backend.route('/tag/<name>', methods=['GET', 'POST'])
def view(name):
    post = Post.query.filter(Post.tag.any(Tag.name == name)).filter(Post.user_id == g.user.id).all()
    # http://stackoverflow.com/questions/21840012/sqlalchemy-select-all-posts-that-has-tags-in-many-to-many
    return render_template('tag/view.html', post=post)

blogdemo/blog/tag/templates/tag/index.html
<!-- extend from layout -->

{% set location = 'tag' %}
{% extends 'layout.html' %}
{% from '_page.html' import message, paginate, status_label %}
{% block title %}mytag{% endblock %}
{% block content %}
<div class="content">
    <div id="body_top" class="Tag">
        <ul id="breadcrumb" class="breadcrumb">
            <li><a href="{{ url_for('account_backend.manage', id=g.user.id) }}">{{ g.user.nickname }}</a></li>
            <li><a href="{{ url_for('admin_backend.index') }}">Admin</a></li>
            <li>Tag</li>
        </ul>
        <hr/>
    </div>
    <div id="body_middle">

        <div class="tag-list">
            {% for tag in tag %}
                <span><a href="{{ url_for('tag_backend.view', name=tag.name) }}">{{ tag.name }} |</span>
            {% endfor %}
        </div>
        <div class="new tag">
            <a href="{{ url_for('tag_backend.new') }}" class="btn btn-inverse">Create New Tag</a>
        </div>
    </div>
</div>
{% endblock %}

blogdemo/blog/tag/templates/tag/new.html
<!-- extend from layout -->

{% extends "layout.html" %}
{% block title %}newtag{% endblock %}

{% block content %}
<div class="content">
    <div id="body_top" class="Tag">
        <ul id="breadcrumb" class="breadcrumb">
            <li><a href="{{ url_for('account_backend.manage', id=g.user.id) }}">{{ g.user.nickname }}</a></li>
            <li><a href="{{ url_for('admin_backend.index') }}">Admin</a></li>
            <li><a href="{{ url_for('tag_backend.index') }}">Tag</a></li>
            <li>Create New Tag</li>
        </ul>
        <hr/>
    </div>
    <div id="body_middle">
        <form action="", method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label }}
            {{ form.name }}
            <br/>

            <input id="submit", name="submit", class="btn btn-inverse", type="submit", value="Create Tag">
        </form>
    </div>
    <div id="showtag">
        {% for tag in taglist %}
            {{ tag.name }}
        {% endfor %}
    </div>
</div>
{% endblock %}

blogdemo/blog/tag/templates/tag/view.html
<!-- extend from layout -->

{% extends 'layout.html' %}
{% from '_page.html' import message, paginate, status_label %}
{% block title %}postbytag{% endblock %}

{% block content %}
<div class="content">
    <div id="body_top" class="Post">
        <ul id="breadcrumb" class="breadcrumb">
            <li><a href="{{ url_for('account_backend.manage', id=g.user.id) }}">{{ g.user.nickname }}</a></li>
            <li><a href="{{ url_for('admin_backend.index') }}">Admin</a></li>
            <li><a href="{{ url_for('tag_backend.index') }}">Tag</a></li>
            <li>Post by Tag</li>
        </ul>
        <hr/>
    </div>
    <div id="body_middle">

        <div class="post-list">
        <table style="width:1000px" class="table table-striped">
            <thead>
                <tr>
                    <th>TITLE</th>
                    <th>AUTHOR</th>
                    <th>CREATED TIME</th>
                    <th>CATEGORY</th>
                    <th>TAG</th>
                    <th>ACTIVE</th>
                </tr>
            </thead>
            <tbody>
                {% for post in post %}
                    <tr>
                        <td><a href="{{ url_for('post_backend.view', id=post.id) }}">{{ post.title }}</a></td>
                        <td>{{ post.author.nickname }}</td>
                        <td>{{ post.created_date }}</td>
                        <td><a href="{{ url_for('category_backend.view', name=post.category.name) }}">{{ post.category_name }}</a></td>
                        <td><span class="tag-links">Tags : 
                            {% for tag in post.tag %}
                                <a href="" title="post in tag" rel="tag">{{ tag.name }}</a>, 
                            {% endfor %}
                            </span>
                        </td>
                        <td>
                            {% if g.user.id == post.user_id %}
                                <a href="{{ url_for('post_backend.edit', id=post.id) }}">edit</a>
                                <a href="{{ url_for('post_backend.delete', id=post.id) }}">delete</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock %}